In [44]:
import numpy as np
import hashlib
import random

In [45]:
# Small example of the partition problem
S = np.array([1, 1, 5, 7])

# Define a list that satisfies the partition problem for a where 
# len(s) == len(a)
# all elements of a are either 1 or -1
# interior product of s and a is 0
a = np.array([1, 1, 1, -1])  # since 1+1+5 - 7 = 0 

## assertions to verify the solution
assert len(S) == len(a)
assert all(x in [1, -1] for x in a)
assert np.dot(S, a) == 0

# w is the partial sum list of the dot product of s and a up to i 
w = get_rolled_sum(S, a)  

# Checking the recursive property for any where i |s[i]| = |w[i + 1] – w[i]|
for i in range(10):
    random_j = random.randint(0, len(S)-1)
    assert abs(S[random_j]) == abs(w[ (random_j + 1) % len(S)] - w[random_j])


    


# Adding some randomness to the proof so that the verifier cannot guess the solution
for i in range(10):
    random_j = random.randint(0, len(S)-1) # random index (picked by the verifier)
    r = random.randint(1, 1000)  # random value (picked by the verifier)
    coin = flip_coin() 
    coin_a = a * coin
    new_w = get_rolled_sum(S, coin_a) + r
    print(new_w)
    assert abs(S[random_j]) == abs(new_w[ (random_j + 1) % len(S)] - new_w[random_j])



[143 142 141 136]
[539 540 541 546]
[749 750 751 756]
[445 446 447 452]
[ 7  8  9 14]
[714 715 716 721]
[137 138 139 144]
[179 178 177 172]
[794 795 796 801]
[139 140 141 146]


In [66]:
# Create a Merkle tree with each element of w as a commitment
def create_merkle_tree(S, a):
    salt = "chillhouse" # secret salt
    random_j = random.randint(0, len(S)-1) # random index (picked by the verifier)
    r = random.randint(1, 1000)  # random value (picked by the verifier)
    coin = flip_coin() 
    coin_a = a * coin
    new_w = get_rolled_sum(S, coin_a) + r
    root = get_salted_merkle_root(new_w, salt)
    print(f"final merkle root: {root}")
    return new_w



In [67]:
# helper to sum and roll w 
def get_rolled_sum(s, a):
        w = np.cumsum(s * a)
        return np.roll(w, 1)

# Flip a coin te create 1 or -1 
def flip_coin():
    return 1 if random.randint(0, 1) == 0 else -1


def hash_pair(a, b):
    combined = (str(a) + str(b)).encode()
    return hashlib.sha256(combined).hexdigest()
